version: '3.1'

services:
  panel_deps:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
      - rabbitmq
    environment:
      SLEEP_LENGTH: 1
      TIMEOUT_LENGTH: 120
    command: db:5432 rabbitmq:5672

  panel:
    env_file:
      - ../configs/env/panel.env
    build:
      context: ../.
      dockerfile: build/panel/Dockerfile
    image: grader-panel:latest
    depends_on:
      - panel_deps
      - rabbitmq
      - db
    ports:
        - "80:8080"
    command: ["/app/panel", "serve", "-v"]

  grader:
    env_file:
      - ../configs/env/grader.env
    build:
      context: ../.
      dockerfile: build/grader/Dockerfile
    image: grader-external:latest
    ports:
      - "8090:8090"
    command: [ "/app/grader", "serve", "-v" ]

  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ../configs/env/database.env
    ports:
      - '5432:5432'
    volumes:
      - ../.tmp/postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

  rabbitmq:
    image: 'rabbitmq:3.9.11-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ../.tmp/rabbitmq_data:/var/lib/rabbitmq

  minio:
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: access_123
      MINIO_SECRET_KEY: secret_123
    command: server /data --console-address ":9001"
    volumes:
      - ../.tmp/minio_data:/data

  redis:
    image: library/redis:6.2.6
